app/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/dashboard', to: 'dashboard#index'
  get '/activities/:id', to: 'activities#show'

  resources :users, only: %i[new create]

  # admin endpoints
  namespace 'admin' do
    get '/themes', to: 'themes#index'
  end

  # authorization endpoints
  namespace 'auth' do
    get '/register', to: 'registrations#new'
    post '/register', to: 'registrations#create'

    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
  end
end

app/app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  # makes Current.user accessible in view files.
  attribute :user
end

app/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :activities

  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
end

app/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def show
    @activity = Activity.find(params[:id])
  end
end

app/app/controllers/admin/themes_controller.rb
# These just exist to play around with colors and not have to clobber assets to
# reload when a new color is used that isn't part of the build.
module Admin
  class ThemesController < ApplicationController
    before_action :require_user_login!
  end
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_user_login!
    # use as `before_action :require_user_login!`
    redirect_to auth_login_path, alert: 'You must be logged in' if Current.user.nil?
  end
end

app/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_user_login!

  def index
    @activities = Current.user.activities
  end
end

app/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/app/helpers/application_helper.rb
module ApplicationHelper
  def flash_classes(flash_type)
    flash_base = 'px-2 py-4 mx-auto font-sans font-medium text-center text-white'
    {
      notice: "bg-gold-600 #{flash_base}",
      error: "bg-crimson-600 #{flash_base}",
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def button_class(options = {})
    variant = options[:variant]
    theme = options[:theme]

    style_button(variant, theme_button(theme))
  end

  private

  def theme_button(theme)
    themes = {
      primary: 'primary',
      secondary: 'secondary',
      transparent: 'transparent',
      dark: 'dark'
    }

    case theme
    when themes[:primary]
      'bg-cobalt-300 hover:bg-cobalt-400 text-white'
    when themes[:secondary]
      'bg-emerald-300 hover:bg-emerald-400 text-white'
    when themes[:transparent]
      'bg-transparent hover:bg-slate-100 text-slate-700'
    when themes[:dark]
      'bg-slate-700 text-white shadow-sm hover:bg-slate-800'
    else
      'bg-white border border-slate-300 shadow-sm hover:bg-slate-100'
    end
  end

  def style_button(variant, theme)
    base = 'font-medium cursor-pointer rounded tr-mt absolute text-center'

    case variant
    when 'large'
      "px-5 py-4 text-lg #{base} #{theme}"
    when 'small'
      "py-2 px-4 text-sm #{base} #{theme}"
    when 'expanded'
      "p-3 w-full block #{base} #{theme}"
    else
      "px-5 py-2 text-base #{base} #{theme}"
    end
  end
end

app/app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/app/helpers/home_helper.rb
module HomeHelper
end

app/app/helpers/session_helper.rb
module SessionHelper
  def logged_in?
    !Current.user.nil?
  end
end

app/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/app/views/activities/show.html.erb
<div class="w-full">
  <div class="mx-auto p-8">
    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
      <%= @activity.name %>
    </h5>
  </div>
</div>

app/app/views/dashboard/index.html.erb
<div class="w-full">
  <div class="mx-auto p-8">
    <div class="flex flex-col md:flex-row justify-center">
      <% @activities.each do |activity| %>
        <a
          href="/activities/<%= activity.id %>"
          class="block p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700"
        >
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            <%= activity.name %>
          </h5>
          <p class="font-normal text-gray-700 dark:text-gray-400">
            <%= activity.description %>
          </p>
        </a>
      <% end %>
    </div>
  </div>
</div>

app/app/views/home/index.html.erb
<div class="w-full">
  <div class="mx-auto p-8">
    <div class="flex flex-col md:flex-row justify-center">
      <div class="md:w-1/2 max-w-md flex flex-col justify-center text-cobalt-500 dark:text-cobalt-300">
        <div class="md:text-4xl text-xl font-black">Track tasks @daily</div>
        <div class="text-xl mt-4">Keep on top of daily activities easily</div>
      </div>
      <div class="md:w-1/2 flex justify-start mt-2 md:justify-end">
        <%= render 'partials/auth/register_form' %>
      </div>
    </div>
  </div>
</div>

app/app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-controller="theme">
  <%= render 'partials/head' %>

  <body class="bg-cobalt-100 dark:bg-cobalt-800 text-slate-600 dark:text-slate-400 font-mono h-screen flex flex-col justify-between">
    <header>
      <%= render 'partials/flash' %>
      <%= render 'partials/nav' %>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer class="relative bg-cobalt-100 dark:bg-cobalt-800 pt-8 pb-6">
      <%= render 'partials/footer' %>
    </footer>
  </body>
</html>

app/app/views/partials/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="<%= flash_classes(type) %>">
    <%= message %>
  </div>
<% end %>

app/app/views/partials/_footer.html.erb
<div class="container mx-auto px-4">
  <% if not logged_in? %>
    <div class="flex flex-wrap text-left lg:text-left">
      <div class="w-full lg:w-6/12 px-4">
        <h4 class="text-3xl fonat-semibold text-slate-500">Under construction</h4>
        <h5 class="text-lg mt-0 mb-2 text-slate-500">
          If you're here it's probably by accident.
        </h5>
      </div>
      <div class="w-full lg:w-6/12 px-4">
        <div class="flex flex-wrap items-top mb-6">
          <div class="w-full lg:w-4/12 px-4 ml-auto">
            <span class="block uppercase text-slate-500 text-sm font-semibold mb-2">Useful Links</span>
            <ul class="list-unstyled">
              <li>
                <a
                  class="text-slate-600 hover:text-slate-800 font-semibold block pb-2 text-sm"
                  href="https://github.com/geoffjay/daily"
                >
                  Github
                </a>
              </li>
            </ul>
          </div>
          <div class="w-full lg:w-4/12 px-4">
            <span class="block uppercase text-slate-500 text-sm font-semibold mb-2">Other Resources</span>
            <ul class="list-unstyled">
              <li>
                <a
                  class="text-slate-600 hover:text-slate-800 font-semibold block pb-2 text-sm"
                  href="https://github.com/geoffjay/daily/blob/main/LICENSE"
                >
                  MIT License
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <hr class="py-2 border-slate-500">
  <% end %>
  <div class="flex flex-wrap md:justify-between justify-center">
    <div class="w-full md:w-4/12 px-4 mx-auto text-center">
      <div class="text-xs text-slate-500 font-semibold py-1">
        Copyright ©
        <span id="get-current-year">2022</span>
        <a href="https://github.com/geoffjay/daily" class="text-slate-500 hover:text-gray-800" target="_blank">@daily by
        <a href="https://github.com/geoffjay" class="text-slate-500 hover:text-slate-800">Geoff Johnson</a>.
      </div>
    </div>
  </div>
</div>

app/app/views/partials/_head.html.erb
 <head>
  <title>
    <%= content_for?(:title) ? yield(:title) : "@daily" %>
  </title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag  "application", "data-turbolinks-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbolinks-track": "reload", defer: true %>
</head>

app/app/views/partials/_header.html.erb
<nav class="bg-sky-100 dark:bg-gray-900 flex flex-row justify-between items-end bg-white">
  <div class="max-w-lg"></div>
  <div class="max-w-lg h-12 pr-2">
    <button
      data-action="click->theme#toggle"
      id="theme-toggle"
      type="button"
      class="text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-0 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-xl text-sm p-3"
    >
      <svg
        id="theme-toggle-dark-icon"
        class="w-6 h-6 hidden"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
      <path
        d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"
      ></path>
      </svg>
      <svg
        id="theme-toggle-light-icon"
        class="w-6 h-6"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
      <path
        d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z"
        fill-rule="evenodd"
        clip-rule="evenodd"
      ></path>
      </svg>
    </button>
  </div>
</nav>

app/app/views/partials/_nav.html.erb
<nav class="bg-cobalt-100 dark:bg-cobalt-800 flex flex-row items-end py-2">
  <div class="w-full"></div>
    <div class="text-slate-500 dark:text-slate-400 text-sm p-3">
      <% if not logged_in? %>
        <%= link_to "login", auth_login_path %>
      <% else %>
        <%= button_to "logout", auth_logout_path, method: :delete %>
      <% end %>
    </div>
  <div class="h-12 pr-2">
    <button
      data-action="click->theme#toggle"
      id="theme-toggle"
      type="button"
      class="text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-700 focus:outline-none focus:ring-0 focus:ring-slate-200 dark:focus:ring-slate-700 rounded-xl text-sm p-3"
    >
      <svg
        id="theme-toggle-dark-icon"
        class="w-6 h-6 hidden"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
      <path
        d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"
      ></path>
      </svg>
      <svg
        id="theme-toggle-light-icon"
        class="w-6 h-6"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      >
      <path
        d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z"
        fill-rule="evenodd"
        clip-rule="evenodd"
      ></path>
      </svg>
    </button>
  </div>
</nav>

app/app/views/partials/components/_card.html.erb
<div class="bg-cobalt-50 border border-slate-300 dark:bg-cobalt-700 dark:border-slate-600 shadow-md flex-auto max-w-sm p-10 pb-20 rounded-lg">
  <%= yield %>
</div>